// Add your Portfolio Details here
module.exports = {
  bio: {
    firstName: "Keshav",
    lastName: "Dulal",
    professionTitle: "Frontend Software Engineer",
    location: "Kathmandu, Nepal",
    interests: [
      "Photography",
      "Filmmaking",
      "Hiking",
      "Swimming",
      "Reading",
      "Playing Guitar",
      "Movies",
    ],
  },
  skillset: {
    languages: [
      "JavaScript",
      "HTML",
      "CSS",
      "Python",
      "Java",
      "C++",
      "C",
      "SQL",
    ],
    frameworks: [
      "React",
      "React Native",
      "Redux",
      "Gatsby",
      "D3",
      "jQuery",
      "Sass",
      "Node",
      "Express",
      "Mongoose",
      "Django",
    ],
    databases: ["PostGreSQL", "MySQL", "MongoDB"],
    learning: ["TypeScript", "GraphQL", "TailWind"],
    tools: [
      "ESlint",
      "Prettier",
      "Parcel",
      "Babel",
      "Webpack",
      "Bash",
      "Git",
      "Postman",
      "Jira",
    ],
  },
  education: {
    bachelors: {
      degree: "B.E. Computer Science Engineering",
      college: "Siddaganga Institute of Technology",
      location: "Tumkur, KA, India",
      duration: "4 Years",
      startEndPeriod: "MAY 2013 - MAY 2016",
    },
  },
  petProjects: [
    {
      name: "Adopt Me",
      descrption: "Find pets for adoption using Petfinder’s API",
      technology: ["React"],
      github: "",
      url: "",
    },
    {
      name: "Exercise Tracker",
      descrption: "Track exercise of multiple users",
      technology: ["Mongo", "Express", "React", "Node"],
      github: "",
      url: "",
    },
    {
      name: "JS Games",
      descrption: "Classic Games using Vanilla JS",
      technology: ["Vanilla JS"],
      github: "",
      url: "",
    },
    {
      name: "2D Mapper",
      descrption: "2 Dimensional Mapping & Navigation Bot using Arduino",
      technology: ["Arduino C"],
      github: "",
      url: "",
    },
  ],
  workExperiences: [
    // {
    //   position: "",
    //   company: "​",
    //   location: "",
    //   summary: "",
    //   duration: "",
    //   durationDetail: "",
    //   technologiesUsed: [],
    //   projects: [],
    //   github:"",
    //   responsibilities: [],
    // },
    {
      position: "Software Engineer",
      company: "​Leapfrog Technology Inc.",
      location: "Kathmanud, Nepal",
      summary:
        "Worked primarily on React Application Development with varying team sizes to build applications for American HealthCare Companies & Educational Institutions",
      duration: "2 Years",
      durationDetail: "SEPT 2016 - AUG 2018",
      technologiesUsed: [
        "React",
        "Redux",
        "Node",
        "Express",
        "PostGreSQL",
        "Django",
        "Rest APIs",
      ],
      github: "",
      projects: [
        "Acustream Ingestion Engine",
        "Bartell Web App Revamp",
        "Eduphoric-Illuminate Server Data Synchronization",
      ],
      responsibilities: [
        "API Integration / Pagination / InfiniteScroll",
        "Searching / Sorting / Selecting / EditingLargeDataSets",
        "Dynamic Data Visualization",
        "FormHandling / Validation / Submission",
        "HIPPA Compliant Web App Development",
        "User Data Tracking, Customization & Management",
        "Delivery & Email Notification Services",
      ],
    },
    {
      position: "Android Intern",
      company: "​ ​Leapfrog Technology Inc.",
      location: "Kathmandu, Nepal",
      summary: "Developed Android Application",
      duration: "3 Months",
      durationDetail: "JUN 2016 - AUG 2016",
      technologiesUsed: ["Android Java"],
      github: "",
      projects: ["Awaz - Musical Instrument Tuner"],
      responsibilities: [
        "Developed Android App (AWAZ) to tune musical instruments",
        "Used Fast Fourier transform (FFT) Algorithm",
        "Worked on a team of 4 and No external libraries were used",
      ],
    },
    {
      position: "Visiting Faculty",
      company: "​Sagarmatha College of Science & Technology",
      location: "Kathmandu, Nepal",
      summary:
        "Taught Computer Networks & Network Security to Diploma & BSc.IT. Students",
      duration: "1 Year 6 Months",
      durationDetail: "FEB 2017 - JULY 2018",
      technologiesUsed: [
        "Computer Networks",
        "Manangin Networks",
        "Network Security",
      ],
      github: "",
      projects: [""],
      responsibilities: [
        "Taught Computer Networks, Managing Networks & Network Security to Diploma Level for 3 semesters",
        "Taught Network Security to B.Sc.IT for a semester",
        "Project Mentor for Final Year B.Sc.IT Students",
      ],
    },
    {
      position: "Cyber Security Intern",
      company: "​Lucideus Tech",
      location: "New Delhi, India",
      summary: "",
      duration: "1 Month",
      durationDetail: "JUN 2014 - JUL 2014",
      technologiesUsed: [],
      projects: [],
      github: "",
      responsibilities: [
        "Selected for on-site summer internship as a finalist of Hack-x-ploit2013",
        "Trained on Cyber Security Practices, Penetration Testing, Network Security, Kali Linux and pitfalls of using of security tools",
      ],
    },
  ],
  socialMedia: {
    github: "https://github.com/keshavdulal",
    stackOverFlow: "https://stackoverflow.com/users/3556531/keshavdulal",
    linkedIn: "https://www.linkedin.com/in/keshavdulal/",
    twitter: "https://twitter.com/keshavdulal",
    // instagram:'',
  },
};
